package org.madgik.utils;

import cc.mallet.pipe.Pipe;
import java.io.*;
import java.util.ArrayList;

import cc.mallet.types.Alphabet;
import cc.mallet.types.FeatureSequence;
import cc.mallet.types.Instance;
import java.util.Arrays;
import java.util.HashSet;

/**
 * Convert a list of strings into a feature sequence
 *
 * @ Target
 */
public class CSV2FeatureSequence extends Pipe {

    public long totalNanos = 0;
    String delimeter = "\\t";
    HashSet<String> stoplist = null;

    private HashSet<String> newDefaultStopList() {
        HashSet<String> sl = new HashSet<String>();
        for (int i = 0; i < stopwords.length; i++) {
            sl.add(stopwords[i]);
        }
        return sl;
    }

    public CSV2FeatureSequence(Alphabet dataDict) {
        super(dataDict, null);
        stoplist = newDefaultStopList();
    }

    public CSV2FeatureSequence(Alphabet dataDict, String delimeter) {
        super(dataDict, null);
        this.delimeter = delimeter;
        stoplist = newDefaultStopList();
    }

    public CSV2FeatureSequence(Alphabet dataDict, String delimeter, String[] words) {
        super(dataDict, null);
        this.delimeter = delimeter;
        stoplist = newDefaultStopList();
        for (int i = 0; i < words.length; i++) {
            stoplist.add(words[i]);
        }
    }

    public CSV2FeatureSequence() {
        super(new Alphabet(), null);
        stoplist = newDefaultStopList();
    }

    public CSV2FeatureSequence(String delimeter) {
        super(new Alphabet(), null);
        this.delimeter = delimeter;
        stoplist = newDefaultStopList();
    }

    public Instance pipe(Instance carrier) {
        // if (!((String) carrier.getTarget()).isEmpty()) {
        long start = System.nanoTime();

        try {

            if (!((String) carrier.getData()).isEmpty()) {
                ArrayList<String> tokens = new ArrayList<String>(Arrays.asList(((String) carrier.getData()).split(delimeter)));
                ArrayList<String> curatedTokens = new ArrayList<String>();

                //String[] tokens = ((String)carrier.getTarget()).split("[ \\t]");
                for (int i = 0; i < tokens.size(); i++) {
                    if (tokens.get(i).length() > 3 && !(stoplist.contains(tokens.get(i).toLowerCase()))) {
                        
                        curatedTokens.add(tokens.get(i));
                    }
                }
                FeatureSequence featureSequence
                        = new FeatureSequence((Alphabet) getAlphabet(), curatedTokens.size());
                for (int i = 0; i < curatedTokens.size(); i++) {                   
                        
                        featureSequence.add(curatedTokens.get(i));
                    
                }

                carrier.setData(featureSequence);
            } else {
                FeatureSequence featureSequence
                        = new FeatureSequence((Alphabet) getAlphabet(), 0);
                carrier.setData(featureSequence);
            }

            totalNanos += System.nanoTime() - start;
        } catch (ClassCastException cce) {
            System.err.println("Expecting ArrayList<String>, found " + carrier.getData().getClass());
        }
        //}
        return carrier;
    }

    static final String[] stopwords
            = {
                "a",
                "able",
                "about",
                "above",
                "according",
                "accordingly",
                "across",
                "actually",
                "after",
                "afterwards",
                "again",
                "against",
                "all",
                "allow",
                "allows",
                "almost",
                "alone",
                "along",
                "already",
                "also",
                "although",
                "always",
                "am",
                "among",
                "amongst",
                "an",
                "and",
                "another",
                "any",
                "anybody",
                "anyhow",
                "anyone",
                "anything",
                "anyway",
                "anyways",
                "anywhere",
                "apart",
                "appear",
                "appreciate",
                "appropriate",
                "are",
                "around",
                "article",
                "articles",
                "as",
                "aside",
                "ask",
                "asking",
                "associated",
                "at",
                "available",
                "away",
                "awfully",
                "b",
                "be",
                "became",
                "because",
                "become",
                "becomes",
                "becoming",
                "been",
                "before",
                "beforehand",
                "behind",
                "being",
                "believe",
                "below",
                "beside",
                "besides",
                "best",
                "better",
                "between",
                "beyond",
                "both",
                "brief",
                "but",
                "by",
                "c",
                "came",
                "can",
                "cannot",
                "cant",
                "cause",
                "causes",
                "certain",
                "certainly",
                "changes",
                "clearly",
                "co",
                "com",
                "come",
                "comes",
                "concerning",
                "consequently",
                "consider",
                "considering",
                "contain",
                "containing",
                "contains",
                "corresponding",
                "could",
                "course",
                "currently",
                "d",
                "definitely",
                "described",
                "despite",
                "did",
                "different",
                "do",
                "does",
                "doing",
                "done",
                "down",
                "downwards",
                "during",
                "e",
                "each",
                "edu",
                "eg",
                "eight",
                "either",
                "else",
                "elsewhere",
                "enough",
                "entirely",
                "especially",
                "et",
                "etc",
                "even",
                "ever",
                "every",
                "everybody",
                "everyone",
                "everything",
                "everywhere",
                "ex",
                "exactly",
                "example",
                "except",
                "f",
                "far",
                "few",
                "fifth",
                "first",
                "five",
                "followed",
                "following",
                "follows",
                "for",
                "former",
                "formerly",
                "forth",
                "four",
                "from",
                "full papers",
                "further",
                "furthermore",
                "g",
                "get",
                "gets",
                "getting",
                "given",
                "gives",
                "go",
                "goes",
                "going",
                "gone",
                "got",
                "gotten",
                "greetings",
                "h",
                "had",
                "happens",
                "hardly",
                "has",
                "have",
                "having",
                "he",
                "hello",
                "help",
                "hence",
                "her",
                "here",
                "hereafter",
                "hereby",
                "herein",
                "hereupon",
                "hers",
                "herself",
                "hi",
                "him",
                "himself",
                "his",
                "hither",
                "hopefully",
                "how",
                "howbeit",
                "however",
                "i",
                "ie",
                "if",
                "ignored",
                "immediate",
                "in",
                "inasmuch",
                "inc",
                "indeed",
                "indicate",
                "indicated",
                "indicates",
                "inner",
                "insofar",
                "instead",
                "into",
                "inward",
                "is",
                "it",
                "its",
                "itself",
                "j",
                "just",
                "k",
                "keep",
                "keeps",
                "kept",
                "know",
                "knows",
                "known",
                "l",
                "last",
                "lately",
                "later",
                "latter",
                "latterly",
                "least",
                "less",
                "lest",
                "let",
                "letter",
                "like",
                "liked",
                "likely",
                "little",
                "look",
                "looking",
                "looks",
                "ltd",
                "m",
                "mainly",
                "many",
                "may",
                "maybe",
                "me",
                "mean",
                "meanwhile",
                "merely",
                "might",
                "more",
                "moreover",
                "most",
                "mostly",
                "much",
                "must",
                "my",
                "myself",
                "n",
                "name",
                "namely",
                "nd",
                "near",
                "nearly",
                "necessary",
                "need",
                "needs",
                "neither",
                "never",
                "nevertheless",
                "new",
                "next",
                "nine",
                "no",
                "nobody",
                "non",
                "none",
                "noone",
                "nor",
                "normally",
                "not",
                "nothing",
                "novel",
                "now",
                "nowhere",
                "o",
                "obviously",
                "of",
                "off",
                "often",
                "oh",
                "ok",
                "okay",
                "old",
                "on",
                "once",
                "one",
                "ones",
                "only",
                "onto",
                "or",
                "original",
                "original research",
                "other",
                "others",
                "otherwise",
                "ought",
                "our",
                "ours",
                "ourselves",
                "out",
                "outside",
                "over",
                "overall",
                "own",
                "p",
                "paper",
                "papers",
                "particular",
                "particularly",
                "per",
                "perhaps",
                "placed",
                "please",
                "plus",
                "possible",
                "presumably",
                "probably",
                "provides",
                "q",
                "que",
                "quite",
                "qv",
                "r",
                "rather",
                "rd",
                "re",
                "really",
                "reasonably",
                "regarding",
                "regardless",
                "regards",
                "relatively",
                "research",
                "research article",
                "research articles",
                "respectively",
                "right",
                "s",
                "said",
                "same",
                "saw",
                "say",
                "saying",
                "says",
                "second",
                "secondly",
                "see",
                "seeing",
                "seem",
                "seemed",
                "seeming",
                "seems",
                "seen",
                "self",
                "selves",
                "sensible",
                "sent",
                "serious",
                "seriously",
                "seven",
                "several",
                "shall",
                "she",
                "should",
                "since",
                "six",
                "so",
                "some",
                "somebody",
                "somehow",
                "someone",
                "something",
                "sometime",
                "sometimes",
                "somewhat",
                "somewhere",
                "soon",
                "sorry",
                "specified",
                "specify",
                "specifying",
                "still",
                "sub",
                "such",
                "sup",
                "sure",
                "t",
                "take",
                "taken",
                "tell",
                "tends",
                "th",
                "than",
                "thank",
                "thanks",
                "thanx",
                "that",
                "thats",
                "the",
                "their",
                "theirs",
                "them",
                "themselves",
                "then",
                "thence",
                "there",
                "thereafter",
                "thereby",
                "therefore",
                "therein",
                "theres",
                "thereupon",
                "these",
                "they",
                "think",
                "third",
                "this",
                "thorough",
                "thoroughly",
                "those",
                "though",
                "three",
                "through",
                "throughout",
                "thru",
                "thus",
                "to",
                "together",
                "too",
                "took",
                "toward",
                "towards",
                "tried",
                "tries",
                "truly",
                "try",
                "trying",
                "twice",
                "two",
                "u",
                "un",
                "under",
                "unfortunately",
                "unless",
                "unlikely",
                "until",
                "unto",
                "up",
                "upon",
                "us",
                "use",
                "used",
                "useful",
                "uses",
                "using",
                "usually",
                "uucp",
                "v",
                "value",
                "various",
                "very",
                "via",
                "viz",
                "vs",
                "w",
                "want",
                "wants",
                "was",
                "way",
                "we",
                "welcome",
                "well",
                "went",
                "were",
                "what",
                "whatever",
                "when",
                "whence",
                "whenever",
                "where",
                "whereafter",
                "whereas",
                "whereby",
                "wherein",
                "whereupon",
                "wherever",
                "whether",
                "which",
                "while",
                "whither",
                "who",
                "whoever",
                "whole",
                "whom",
                "whose",
                "why",
                "will",
                "willing",
                "wish",
                "with",
                "within",
                "without",
                "wonder",
                "would",
                "would",
                "x",
                "y",
                "yes",
                "yet",
                "you",
                "your",
                "yours",
                "yourself",
                "yourselves",
                "z",
                "zero",
                // stop words for paper abstracts
                "abstract",
                "paper",
                "presents",
                "discuss",
                "discusses",
                "conclude",
                "concludes",
                "based",
                "approach"
            };

    static final long serialVersionUID = 1;
}
